- name: Install Elasticsearch and Search Guard
  hosts: es-nodes #from inventory
  become: true
  roles:
    - { role: search-guard-ansible }
  pre_tasks:
    - name: Add IP address of all hosts to all hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }}"
        state: present
      when: hostvars[item].inventory_hostname is defined
      with_items: "{{ groups.all }}"
    - name: Copy SSL certificates
      copy:
        src: "{{ playbook_dir }}/files/certificates"
        dest: "/etc/elasticsearch/{{ inventory_hostname }}"
  post_tasks:
    - name: Copy sgconfig
      copy:
        src: "{{ playbook_dir }}/files/sgconfig"
        dest: "/etc/elasticsearch"
      notify: execute sgadmin

- name: Execute health checks
  hosts: es-nodes
  become: true
  tasks:
    - name: Check health via sgadmin
      shell: "/usr/share/elasticsearch/plugins/search-guard-6/tools/sgadmin.sh -nhnv -cn {{ clustername }} -h {{ inventory_hostname }} -si -key /etc/elasticsearch/{{ inventory_hostname }}/certificates/admin_cert_key.pem -cert /etc/elasticsearch/{{ inventory_hostname }}/certificates/admin_cert.pem -cacert /etc/elasticsearch/{{ inventory_hostname }}/certificates/ca_cert.pem"
      changed_when: False
    - name: Check health via health endpoint
      uri:
        url: "https://{{ inventory_hostname }}:9200/_searchguard/health"
        method: GET
        user: admin
        password: admin
        validate_certs: no
      changed_when: False